public class testclass {

    public string name;
    public string sex;
    public string address;
    public integer age;
    public integer size;
    public date dob;
    public void display()
    {
        System.debug('name:' +name);
        System.debug('Sex :' +sex);
        System.debug('address :' +address);
        System.debug('age :' +age);
        System.debug('size :' +size);
        System.debug('dob' +dob);
    }
}
